/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/FLHrQepdQ8N
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { SheetTrigger, SheetTitle, SheetDescription, SheetHeader, SheetContent, Sheet } from "@/components/ui/sheet"
import { CollapsibleTrigger, CollapsibleContent, Collapsible } from "@/components/ui/collapsible"
import { Badge } from "@/components/ui/badge"
import { DropdownMenuTrigger, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuItem, DropdownMenuContent, DropdownMenu } from "@/components/ui/dropdown-menu"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { SelectValue, SelectTrigger, SelectContent, Select } from "@/components/ui/select"
import { BellIcon, ChevronRightIcon, LogOutIcon, MenuIcon, SettingsIcon, ShoppingCartIcon, UserIcon } from "lucide-react"
import { GitHubLogoIcon, InstagramLogoIcon, TwitterLogoIcon } from "@radix-ui/react-icons"

export function Farm2() {
  return (
    <div className="min-h-screen bg-[#f5f5f5] dark:bg-[#1a1a1a] text-[#333] dark:text-[#f5f5f5]">
      <header className="bg-teal-500 dark:bg-teal-700 py-4 px-6 md:px-8 lg:px-10 flex items-center justify-between">
        <Link className="text-2xl font-bold hidden md:block" href="#">
          Farm
        </Link>
        <Sheet>
          <SheetTrigger asChild>
            <Button className="md:hidden" size="icon" variant="ghost">
              <MenuIcon className="w-6 h-6" />
              <span className="sr-only">Toggle navigation menu</span>
            </Button>
          </SheetTrigger>
          <SheetContent side="left">
            <SheetHeader>
              <SheetTitle>Menu</SheetTitle>
              <SheetDescription>Navigate through our website</SheetDescription>
            </SheetHeader>
            <Collapsible>
              <CollapsibleTrigger className="flex items-center justify-between">
                Shop
                <ChevronRightIcon className="w-4 h-4" />
              </CollapsibleTrigger>
              <CollapsibleContent className="bg-yellow-50">
                <Link className="block py-2 px-4 hover:bg-yellow-100" href="#">
                  Fruits
                </Link>
                <Link className="block py-2 px-4 hover:bg-yellow-100" href="#">
                  Vegetables
                </Link>
                <Link className="block py-2 px-4 hover:bg-yellow-100" href="#">
                  Dairy
                </Link>
              </CollapsibleContent>
            </Collapsible>
            <Collapsible>
              <CollapsibleTrigger className="flex items-center justify-between">
                About
                <ChevronRightIcon className="w-4 h-4" />
              </CollapsibleTrigger>
              <CollapsibleContent className="bg-yellow-50">
                <Link className="block py-2 px-4 hover:bg-yellow-100" href="#">
                  Our Story
                </Link>
                <Link className="block py-2 px-4 hover:bg-yellow-100" href="#">
                  Our Farms
                </Link>
                <Link className="block py-2 px-4 hover:bg-yellow-100" href="#">
                  Our Values
                </Link>
              </CollapsibleContent>
            </Collapsible>
            <Link className="block py-2 px-4 hover:bg-yellow-100" href="#">
              Contact
            </Link>
          </SheetContent>
        </Sheet>
        <div className="flex items-center gap-4">
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button size="icon" variant="ghost">
                <ShoppingCartIcon className="w-6 h-6" />
                <Badge className="absolute top-0 right-0 bg-red-500 text-white rounded-full px-1.5 py-0.5 text-xs" />
                <span className="sr-only">Cart</span>
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="end">
              <DropdownMenuLabel>Cart</DropdownMenuLabel>
              <DropdownMenuSeparator />
              <DropdownMenuItem>Your cart is empty</DropdownMenuItem>
            </DropdownMenuContent>
          </DropdownMenu>
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button size="icon" variant="ghost">
                <UserIcon className="w-6 h-6" />
                <span className="sr-only">User Menu</span>
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="end">
              <DropdownMenuLabel>My Account</DropdownMenuLabel>
              <DropdownMenuSeparator />
              <DropdownMenuItem>
                <SettingsIcon className="w-4 h-4 mr-2" />
                Settings
              </DropdownMenuItem>
              <DropdownMenuItem>
                <LogOutIcon className="w-4 h-4 mr-2" />
                Logout
              </DropdownMenuItem>
            </DropdownMenuContent>
          </DropdownMenu>
          <Button size="icon" variant="ghost">
            <BellIcon className="w-6 h-6" />
            <span className="sr-only">Notifications</span>
          </Button>
        </div>
      </header>
      <main className="px-4 md:px-8 lg:px-10 py-8">
        <div className="mb-6">
          <Collapsible>
            <CollapsibleTrigger className="flex items-center justify-between w-full bg-green-500 dark:bg-green-700 text-white px-4 py-2 rounded-lg">
              <span>Filters</span>
            </CollapsibleTrigger>
            <CollapsibleContent className="p-4 bg-white dark:bg-[#2c2c2c] rounded-lg shadow-md">
              <div className="flex flex-col md:flex-row justify-between mb-6">
                <div className="mb-4 md:mb-0 md:mr-4">
                  <Label className="mb-2" htmlFor="crop-filter">
                    Filter by Crop
                  </Label>
                  <Input id="crop-filter" placeholder="Filter by crop" />
                </div>
                <div>
                  <Label className="mb-2" htmlFor="location-filter">
                    Filter by Location
                  </Label>
                  <Input id="location-filter" placeholder="Filter by location" />
                </div>
              </div>
            </CollapsibleContent>
          </Collapsible>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6" />
        <div className="mt-8">
          <h2 className="text-2xl font-bold mb-4">Checkout</h2>
          <div className="bg-white dark:bg-[#2c2c2c] rounded-lg shadow-md p-4">
            <div className="mb-4">
              <h3 className="text-lg font-bold">Items in Cart</h3>
              <ul />
            </div>
            <div className="flex justify-between items-center">
              <span className="text-lg font-bold">Total Cost:</span>
              <span className="text-2xl font-bold">$</span>
            </div>
            <Button className="mt-4 w-full">Proceed to Checkout</Button>
          </div>
        </div>
      </main>
      <footer className="bg-teal-500 dark:bg-teal-700 text-white py-4 px-6 md:px-8 lg:px-10 flex items-center justify-between">
        <div className="text-sm">© 2024 FarmFresh. All rights reserved.</div>
        <div className="flex items-center gap-4">
          <Link className="hover:text-gray-200" href="#">
            <TwitterLogoIcon className="w-6 h-6" />
            <span className="sr-only">Twitter</span>
          </Link>
          <Link className="hover:text-gray-200" href="#">
            <GitHubLogoIcon className="w-6 h-6" />
            <span className="sr-only">Facebook</span>
          </Link>
          <Link className="hover:text-gray-200" href="#">
            <InstagramLogoIcon className="w-6 h-6" />
            <span className="sr-only">Instagram</span>
          </Link>
        </div>
      </footer>
      <div>
        <div>
          <div>Select Destination</div>
          <div>Please choose the location where you want your order to be delivered.</div>
        </div>
        <div>
          <Select>
            <SelectTrigger>
              <SelectValue placeholder="Select a location" />
            </SelectTrigger>
            <SelectContent />
          </Select>
        </div>
        <div>
          <Button variant="outline">Cancel</Button>
          <Button>Confirm</Button>
        </div>
      </div>
    </div>
  )
}
